occlum/occlum

src/pal/src/pal_enclave.c

The address of the `token` should be used by fwrite().
Signed-off-by: Tianjia Zhang <tianjia.zhang@linux.alibaba.com>

pal: Fix typo error in saving token file

---

src/pal/src/pal_enclave.c

On lightweight Linux distribution, like alpine, getpwuid()
returns NULL, and errno is ENOENT, this patch fix crash
caused by this situation.
Signed-off-by: Tianjia Zhang <tianjia.zhang@linux.alibaba.com>

pal: Fix crash caused by getpwuid() returning NULL

---

.github/workflows/demo_test.yml

Enable all demo tests except: 
- gdb (may not need)
- TensorFlow lite (separate to other patches)
- openVINO (separate to other patches)
- Remote attestation (Need more investigation)
- Python (soon, could ship together with next release's image)

Add demo test for CI

---

.github/workflows/build_and_push_ci_image.yml
.github/workflows/demo_test.yml
tools/docker/ci/Dockerfile.grpc
tools/docker/ci/Dockerfile.openvino

This commit mainly does two things:
1.  Add a manual trigger action to build images for demo CI. Once it merged, it will look like below and only the project owner can trigger building new image for demo CI.
2. Add openvino and tflite test

Enable TFLite and OpenVINO test for CI and add CI image build action

---

Makefile
tools/installer/deb/occlum/rules

man cp：
> -a, --archive
same as -dR --preserve=all
-d
same as --no-dereference --preserve=links
-P, --no-dereference
never follow symbolic links in SOURCE
--preserve[=ATTR_LIST]
preserve the specified attributes (default: mode,ownership,timestamps), if possible additional attributes: context, links, xattr, all

Fix copy softlink for make install and deb installer

---

src/Enclave.edl
src/libos/src/events/event.rs
src/libos/src/events/host_event_fd.rs
src/libos/src/events/mod.rs
src/libos/src/events/notifier.rs
src/libos/src/events/observer.rs
src/libos/src/events/waiter.rs
src/libos/src/events/waiter_queue.rs
src/libos/src/events/waiter_queue_observer.rs
src/libos/src/lib.rs
src/libos/src/process/thread/builder.rs
src/libos/src/process/thread/mod.rs
src/libos/src/time/mod.rs
src/pal/src/ocalls/event.c
src/pal/src/ocalls/fs.c
src/pal/src/pal_syscall.h

An event can be anything ranging from the exit of a process (interesting
to `wait4`) to the arrival of a blocked signal (interesting to
`sigwaitinfo`), from the completion of a file operation (interesting to
`epoll`) to the change of a file status (interesting to `inotify`).
To meet the event-related demands from various subsystems, this event
subsystem is designed to provide a set of general-purpose primitives:
* `Waiter`, `Waker`, and `WaiterQueue` are primitives to put threads
to sleep and later wake them up.
* `Event`, `Observer`, and `Notifier` are primitives to handle and
broadcast events.
* `WaiterQueueObserver` implements the common pattern of waking up
threads once some interesting events happen.

Add the event subsystem

---

demos/golang/grpc_benchmark/README.md
demos/golang/grpc_benchmark/download_and_build_grpc_benchmark.sh
demos/golang/grpc_benchmark/run_occlum_bench.sh

Copied and Modified the google.golang.org/grpc/benchmark/run_bench.sh to
support the benchmark with occlum.

Add the gRPC-golang benchmark

---

demos/golang/grpc_benchmark/run_occlum_bench.sh

Exec parses the script according to the shebang.

Put the shebang in the front of run_occlum_bench.sh

---

Makefile
src/run/Makefile
tools/installer/deb/toolchains/gcc/rules
tools/installer/rpm/occlum-filelist

1. Fix repeatedly linking dynamic libraries for occlum-run
2. Fix gcc toolchain deb package build error
3. Remove redundant file from installer file list
4. Change symlink target path to relative path

Fix package build error

---

src/exec/Makefile
src/libos/Makefile
tools/docker/Dockerfile.centos7.5
tools/docker/Dockerfile.centos8.1
tools/docker/Dockerfile.ubuntu18.04

Using sccache accelerates the compilation when the cache is hit. Especially, `make clean` and then `make` saves seconds.

Compile using sccache if it is installed

---

src/pal/src/ocalls/event.c
src/pal/src/ocalls/sched.c
src/pal/src/ocalls/signal.c
src/pal/src/ocalls/spawn.c
src/pal/src/pal_api.c
src/pal/src/pal_syscall.h
src/pal/src/pal_thread_counter.c

`tgkill` and `gettid` are defined in the high-version glibc. Refer to the man page of `tgkill` and `gettid` for more details. Besides, C macro is usually upper-case. This conflict is found in alios7u2.

Fix the conflict of symbols with glibc

---

src/libos/src/exception/cpuid.rs
test/cpuid/main.c

1.  `>>` has higher precedence than `&`. Use parentheses to conduct `&` first;
2. In the latest Intel software developer's manual, cpuid leaf 06H EDX
is related to the logical processor.

Fix two cpuid bugs

---

src/libos/src/fs/dev_fs/dev_null.rs
src/libos/src/fs/dev_fs/dev_random.rs
src/libos/src/fs/dev_fs/dev_sgx/mod.rs
src/libos/src/fs/dev_fs/dev_zero.rs
src/libos/src/fs/events.rs
src/libos/src/net/io_multiplexing/epoll/host_file_epoller.rs
src/libos/src/net/io_multiplexing/epoll/mod.rs
src/libos/src/net/io_multiplexing/mod.rs
src/libos/src/net/io_multiplexing/poll_new/event_monitor.rs
src/libos/src/net/io_multiplexing/poll_new/mod.rs
src/libos/src/net/mod.rs
src/libos/src/net/syscalls.rs
src/libos/src/syscall/mod.rs
test/pipe/main.c
test/unix_socket/main.c

Based on the new event subsystem, the new poll implementation can work with any file types, including LibOS files and host files.
The new poll syscall can be found [here](https://github.com/occlum/occlum/blob/ea806f33690abe986b760672b56cf2b44f9125da/src/libos/src/net/io_multiplexing/poll_new/mod.rs#L13), which is as simple as 100 lines. The is because the heavy-lifting is done by a helper type named [`EventMonitor`](https://github.com/occlum/occlum/blob/ea806f33690abe986b760672b56cf2b44f9125da/src/libos/src/net/io_multiplexing/poll_new/event_monitor.rs#L16), whose code is commented intensively.
The old poll implementation has not been removed (yet) as some code still relies on it, for example, the unix sockets. The unix sockets will be soon rewritten based the primitives provided by the …

Add the new poll implementation

---

.github/workflows/demo_test.yml
.github/workflows/hw_mode_test.yml
demos/python/run_python_on_occlum.sh

Using tcmalloc could consume more heap. Enlarging kernel heap allocation can fix this.
Also, print results for Python test.

Fix Python test malloc failure on SGX machine

---

src/libos/src/fs/file_ops/close.rs
src/libos/src/fs/file_table.rs
src/libos/src/fs/mod.rs
src/libos/src/net/io_multiplexing/epoll/epoll_file.rs

Usually, files are unregistered from an epoll file via the `EPOLL_CTL_DEL` command explicitly. But for the sake of users' convenience, Linux supports unregistering a file automatically from the epoll files that monitor the file when the file is closed. This commit adds this capability.

Unregister a file from epoll files when the file is closed

---

src/libos/src/fs/event_file.rs
src/libos/src/fs/host_fd.rs
src/libos/src/net/io_multiplexing/epoll/host_file_epoller.rs
src/libos/src/net/socket/host_socket/mod.rs

This PR should be able fix issue #231 although I haven't been able to reproduce the bug reported in the issue. With that said, this PR fixes a race condition (in very rare cases) that causes `HostFd::new` to panic.
By the way, I have repeated the server and eventfd tests, which are supposed to be able to trigger the bug according to #231, for 500 times. No panics occur. So I think the bug should have been fixed.

Use HostFd to manage the lifetime of host OS resources

---

src/sgxenv.mk

The current Tcmalloc has memory leak issue. So change it as optional. By
default, dlmalloc is used. Enable tcmalloc with below command:
make TCMALLOC=Y

Change Tcmalloc as optional feature

---

src/libos/src/fs/channel.rs

This is a bugfix for #244 . It ensures that when an object of Producer/Consumer for channels is dropped, its shutdown method is called automatically. This ensures that the peer of a Producer/Consumer gets notified and won't wait indefinitely.

Fix a bug of channels

---

test/Occlum.json

The CI test randomly failed for the lack of heap.

Enlarge the kernel heap size in make test

---

.github/workflows/hw_mode_test.yml

Currently, SGX hardware CI tests only run when a new commit is pushed to an `occlum/occlum` 's branch. This commit expands the trigger type to pull request with labeled `SGX-hardware-test-required`. Since only the owners have the privilege to label the pull request, this won't make the hardware test insecure.

Change SGX hardware mode CI test trigger type

---

src/exec/src/bin/occlum_exec_client.rs
src/exec/src/bin/occlum_exec_server.rs
src/exec/src/lib.rs

The UDS path length should less than sun_path length, it
is too short in some cases. So use a file under /tmp folder
as the UDS path.

Fix the UDS path is too long issue

---

src/Enclave.edl
src/libos/Cargo.toml
src/libos/Makefile
src/libos/src/fs/dev_fs/dev_sgx/consts.rs
src/libos/src/fs/dev_fs/dev_sgx/mod.rs
src/libos/src/util/sgx/dcap/mod.rs
src/libos/src/util/sgx/dcap/quote_generator.rs
src/libos/src/util/sgx/dcap/quote_verifier.rs
src/libos/src/util/sgx/epid/attestation_agent.rs
src/libos/src/util/sgx/epid/mod.rs
src/libos/src/util/sgx/epid/quote.rs
src/libos/src/util/sgx/mod.rs
src/pal/Makefile
src/pal/src/ocalls/attestation.c
test/ioctl/Makefile
test/ioctl/main.c
tools/docker/Dockerfile.centos8.1
tools/docker/Dockerfile.ubuntu18.04

1. Five new ioctl commands of /dev/sgx are provided for occlum
applications to securely get and verify DCAP quote;
2. Not all the functions of the intel DCAP package are open to
developers to simplify the DCAP usage;
3. The test may only run on the platform with DCAP driver installed;
4. A macro OCCLUM_DISABLE_DCAP is used to separate the DCAP code from
the other code.

Add support for DCAP

---

test/ioctl/main.c

Skip DCAP test when DCAP driver is not detected

---

src/libos/src/fs/file_ops/chmod.rs
src/libos/src/fs/file_ops/mod.rs
src/libos/src/fs/syscalls.rs
src/libos/src/syscall/mod.rs

The flags argument of fchmodat syscall is handled by the wrapper function in libc already, so Occlum does not need to accept this argument.

Remove the flags argument handling in fchmodat syscall

---

.github/workflows/package_repo_setup_and_test.yml

This test https://github.com/occlum/occlum/actions/runs/436974476 fails because DCAP packages are not installed correctly. However, the Occlum packages uploaded are correct and my local test can pass after installing DCAP packages provided by Intel.

Fix package repository test failure due to lack of DCAP packages

---

test/sched/main.c

The number of available cpu is fetched from `sched_getaffinity()`, it may be less than all online cpus, we should not assume that the number is equal to all online cpus.

Fix the sched test when available cpu is less than online cpu

---

tools/docker/ci/Dockerfile.grpc
tools/docker/ci/Dockerfile.openvino

The demo dir location in the CI image is wrong. This commit fixed this.

Fix gRPC and OpenVINO CI image demo location

---

.gitmodules
src/libos/Cargo.lock
src/libos/Cargo.toml
src/libos/src/lib.rs
src/libos/src/process/do_spawn/exec_loader.rs
src/libos/src/process/do_spawn/mod.rs
src/libos/src/process/elf_file.rs
src/libos/src/vm/process_vm.rs

Libos now Only read in headers and needed segments. Also reduce a memory
copy.

Use goblin as elf parser and only load segments on demand 

---

src/libos/src/vm/process_vm.rs
test/mmap/main.c

Fix: https://github.com/occlum/occlum/issues/327

Fix false alarm on non-page-aligned size for mprotect

---

demos/fish/run_per_process_config_test.sh
demos/fish/test_per_process_config.sh
demos/java/run_java_on_occlum.sh
etc/template/Occlum.json
src/libos/src/vm/process_vm.rs
src/libos/src/vm/user_space_vm.rs
src/libos/src/vm/vm_manager.rs
src/libos/src/vm/vm_perms.rs
test/Occlum.json

This branch is based on https://github.com/occlum/occlum/pull/324.
Previously mprotect ocall count in a make test case:
hello_world: 6
mmap: 318
With this commit (ea0aa3c), mprotect ocall count in a make test case:
hello_world: 4
mmap: 45

Reduce redundant mprotect ocall

---

test/include/test.h

When encountering an error in make test and THROW_ERROR is called, output will be like this:
`ERROR:spawn process error in func test_sched_xetaffinity_with_child_pid at line 100 of file main.c with errno 12: Out of memory`

Add errno info when return error in make test

---

src/libos/src/sched/syscalls.rs

The affinity array should be compared with the CpuSet::len

Fix affinity array size incorrect issue

---

.github/workflows/package_repo_setup_and_test.yml
tools/installer/rpm/occlum-filelist
tools/installer/rpm/occlum.spec

This commit fixed three errors:
(1) Fix Github action virtual environment out of free disk space
(2) Add "init" binary which is recently added for the encrypted image
(3) Bypass "Missing build-id" error when RPM packaging
This change has been verified in my local repository.

Fix installer for new release

---

src/pal/src/pal_api.c
src/pal/src/pal_check_fsgsbase.c
src/pal/src/pal_check_fsgsbase.h

Now, we are in a complex situation that FSGSBASE instructions might or might not be supported in the OS. Add this new tool for users to do a quick check on whether it is supported.
In the future, we can add more checks and diagnose in this subcommand to include more info that we are interested in. Thus, we can let users run this command if they can't run Occlum successfully. And If they can't fix for themselves, they can paste the log to GitHub issues and it would be easier for us to diagnose for them.

Add detection for FSGSBASE enablement in PAL

---

.github/workflows/demo_test.yml

Remove workarounds in Demo CI, because simulation mode has been updated.
Remove the duplicated make test.

Remove workarounds in Demo CI

---

tools/docker/Dockerfile.centos8.2
tools/docker/start_aesm.sh

1. Run AESM at background
2. CentOS docker image missed aesm-launch-plugin

Fix docker image for SGX1 HW

---

src/libos/src/process/do_spawn/exec_loader.rs

Previously, error messages when `parse_elf_hdr ` are not exported.
Running an elf file without -fPIE compiling option will look like this:

Export error message when parsing Elf header

---

tools/occlum
tools/occlum_build.mk

Remove "--always-remake" option and add "--no-builtin-rules" to avoid
mistakenly rebuild unwanted targets.
Fixed issue #430

Fix occlum build "-f" option mistakenly rebuild other targets

---

src/libos/src/fs/file_ops/access.rs
src/libos/src/fs/file_ops/chmod.rs
src/libos/src/fs/file_ops/chown.rs
src/libos/src/fs/file_ops/fspath.rs
src/libos/src/fs/file_ops/link.rs
src/libos/src/fs/file_ops/mkdir.rs
src/libos/src/fs/file_ops/open.rs
src/libos/src/fs/file_ops/rename.rs
src/libos/src/fs/file_ops/rmdir.rs
src/libos/src/fs/file_ops/stat.rs
src/libos/src/fs/file_ops/symlink.rs
src/libos/src/fs/file_ops/truncate.rs
src/libos/src/fs/file_ops/unlink.rs
src/libos/src/fs/fs_ops/chdir.rs
src/libos/src/fs/fs_ops/getcwd.rs
src/libos/src/fs/procfs/pid_inode.rs
src/libos/src/net/socket/unix/addr.rs
src/libos/src/process/do_spawn/exec_loader.rs
src/libos/src/process/do_spawn/mod.rs
src/libos/src/process/mod.rs
src/libos/src/util/sync/rw_lock/mod.rs
test/procfs/main.c

When process lookup the inode through `lookup_inode` of FsView, It has to hold the lock of FsView, meanwhile, the symlink inode of procfs may access the `cwd` or `root` of FsView when dereferencing symlinks. Apparently, there is a deadlock of FsView.
Change the lock of FsView from `SgxMutex` to `RwLock`, to access the `cwd` and `root` of FsView concurrently.

Fix a potential deadlock when dereference procfs's symlink

---

tools/occlum

Some user using host AESM, so Occlum should only check the socket file instead of the AESM process before running.

Check AESM status with aesm socket file

---

README.md

Reference:
[1] https://github.com/intel/linux-sgx/blob/f1fcf9175d58d28bbee576438d9b68ecf93f5e4e/psw/urts/linux/edmm_utility.cpp#L89
[2] https://www.kernel.org/doc/html/v5.11/x86/sgx.html#enclave-build-functions

Fix readme doc for new dcap or in-tree kernel driver

---

.github/workflows/demo_test.yml
tools/occlum

Checkout here for the implementation of `__get_nprocs `,
https://github.com/bminor/glibc/blob/glibc-2.27/sysdeps/unix/sysv/linux/getsysstats.c#L214
Since `/proc/cpuinfo` is supported in Occlum, we can remove the online file from the image.

Remove the cpu online file for glibc

---

.github/workflows/build_and_push_aliyunlinux_image.yml

There is some known issue for aliyunlinux3 base image. So change default image back to aliyunlinux2.

Use aliyunlinux2 as default image for aliyunlinux

---

src/libos/src/sched/cpu_set.rs
src/libos/src/sched/syscalls.rs

The return value of the raw sched_getaffinity syscall must be an integer multiple of sizeof(long) in Linux.
Linux code: 
```
unsigned int retlen = min(len, cpumask_size());
static inline unsigned int cpumask_size(void)
{
return BITS_TO_LONGS(nr_cpumask_bits) * sizeof(long);
}
```

Fix the return value of sched_getaffinity.

---

src/libos/src/vm/process_vm.rs
src/libos/src/vm/user_space_vm.rs
src/libos/src/vm/vm_layout.rs

(1) Fix uninitialized elf memory for loadable segment
(2) Fix an error when calculating elf memory usage
VMLayout was mistakenly used to calculate the memory usage. This
commit is to fix this and separate VMLayout "add" and "extend"
methods.
(3) Don't allocate extra memory if already aligned

Fix some process VM error when enabling GCC 10

---

.github/workflows/build_and_push_aliyunlinux_image.yml
tools/docker/Dockerfile.aliyunlinux3
tools/docker/build_image.sh

After fixing some process VM errors for GCC 10, alinux3 can work now.
I have tested with my own repo. Please check out here:https://github.com/jessehui/occlum/actions/runs/1054798983
Please merge #548 first. Then I will do a rebase.

Re-enable aliyunlinux 3 image as default aliyunlinux image

---

src/libos/src/fs/syscalls.rs
test/mkdir/main.c

`getcwd` should return the length of buffer filled

Fix the wrong value returned from getcwd

---

.github/workflows/rune_test.yml
demos/deployment/Dockerfile_template.centos8.2
demos/deployment/Dockerfile_template.ubuntu18.04
tools/occlum

In default only HW mode package is supported. 
But in some cases, such as debug purpose or on no HW SGX env, simulation mode package may be required as well.
Adding a "--debug" flag in "occlum package" to support simulation mode occlum image package.

Add similation and debug mode occlum package check and support

---

Makefile

If I add SGX_SDK environment to /etc/profile or other environment path then SGX_SDK should not be changed.Maybe the directory which I want to install is not '/opt/intel/'

SGX_SDK environment should not be changed if it is already set

---

demos/cluster_serving/environment.sh
demos/cluster_serving/install-dependencies.sh
demos/cluster_serving/start-flink-jobmanager.sh
demos/cluster_serving/start-flink-taskmanager.sh
demos/cluster_serving/start-redis.sh

* Change hard code classpath into path/*, such that changing Flink version will not break this demo.
* Reduce redis memory
* Change Flink version to 1.11.3
* Add no_proxy to avoid network problem in proxy

Fix Cluster Serving demo classpath

---

.github/workflows/demo_test.yml

For successful sofaboot, every components should be in "UP" status, not "DOWN" status.

Update sofaboot demo result check command

---

src/libos/src/fs/inode_file.rs

According to https://man7.org/linux/man-pages/man2/write.2.html and https://man7.org/linux/man-pages/man2/read.2.html, If the file is not opened for writing or reading, should return EBADF.

Fix the return error code of file operations

---

.github/workflows/code_coverage.yaml

Also increase the nap time to 120s from 60s to make all demos pass.
The reason to remove flink and sofatboot demo is there was no obvious code coverage improvement with these two demos.
But to make these two demos pass, nap time has to be increased to 180s and some clean steps has to be taken before the tests, such as "pkill occlum".

Remove flink and sofatboot demo for code coverage report

---

tools/toolchains/bash/build.sh

Make sure bash is built as PIE for differernt OS

---

demos/remote_attestation/dcap/c_app/dcap_quote.h
demos/remote_attestation/dcap/dcap_lib/Cargo.toml

1. When including the header file in C++ project, the linker
cannot find the functions.
2. Add the staticlib building.

Fix the C++ Link issue and Add the static lib

---

demos/remote_attestation/dcap/c_app/dcap_quote.h

Without the fix, the default dcap demo couldn't pass build.

Fix the compile error when including dcap_quote.h in pure C program

---

demos/pytorch/README.md

There are two errors in PyTorch demo's README.md
- Step 2 and 3 should be executed inside the container, not on host.
- The demo's dir is ` /root/demos/pytorch`, not ` /root/occlum/demos/pytorch`

doc(demos/PyTorch): fix wrong message in README

---

src/libos/src/fs/file_ops/ioctl/builtin.rs
src/libos/src/fs/file_ops/ioctl/mod.rs
src/libos/src/fs/stdio.rs

This implementation is different from what was done in NGO due to different ioctl implementation.

Fix TCGETS/TCSETS using wrong termios type definition

---

src/libos/src/fs/hostfs.rs
src/libos/src/time/mod.rs

Cannot get correct time when running java/c program in occlum due to incompatible timespec convertion from Rust to C. Actually, the ability of getting correct time is very important for some applications, for example, using JAVA FileLock which repetitively check file last-change time. This bug would make those application rush to error.
The bug is caused by incompatible timespec conversion in Rust ({i64, i32}) and C ({long, long}). When C program invokes a Rust lib to get one variable (e.g., info) including  timespec-type value (info.atime), the result in C  is not same to that generated in Rust.
Remember to check [#40](https://github.com/occlum/sefs/pull/40#issue-1098863814) which also includes one sample code.
In additional, thanks to @liqinggd for his generous help.

BUG: incompatible timespec convertion from rust to c

---

demos/linux-ltp/syscalls-occlum

The Linux-ltp getdtablesize01 opens "/etc/hosts" file as many, which run out of memory if without limitations. Now I have implemented rlimit_nofile limitations for opening files, but it would cause more failure in gvisor tests. The reasons have been listed in the [issue865](https://github.com/occlum/occlum/issues/865). Therefore, for ensuring CI test integrity as quickly, the Linux-ltp getdtablesize01 test is removed.

Remove Linux-ltp getdtablesize01 syscalls test

---

.github/workflows/package_repo_setup_and_test.yml

This commit is the same as the branch: https://github.com/occlum/occlum/tree/fix_package_repo
and has been tested here: https://github.com/occlum/occlum/runs/6121286608?check_suite_focus=true.

Fix Deb package rep setup actions

---

src/Enclave.edl
src/libos/include/edl/occlum_edl_types.h
src/libos/src/util/host_file_util.rs
src/pal/include/occlum_pal_api.h
src/pal/src/pal_api.c
src/pal/src/pal_load_file.c
src/pal/src/pal_load_file.h

When parsing host files into enclave, the host_file_buffer is shadow copied from untrusted memory, which is unsafe. Thus, the parsing methods are changed to deep copy.

Deep copy host file

---

src/libos/src/lib.rs
src/libos/src/util/sync/rw_lock/inner.rs
src/libos/src/util/sync/rw_lock/mod.rs

1. Improve readability
2. Ease the restriction on memory ordering for better performance
This rwlock implementation is mostly the same as the rwlock implementation provided in NGO async-rt (https://github.com/occlum/ngo/pull/244).

Refactor rwlock implementation

---

.github/workflows/demo_test.yml

The previous error is due to the early kill of the container.
Heavily tested here: https://github.com/jessehui/occlum/actions/runs/2634970852

Fix pytorch demo CI

---

src/libos/src/fs/hostfs.rs
test/hostfs/main.c

There are no sync methods about untrusted dir, so we do nothing.
This commit may fix the issue https://github.com/occlum/occlum/issues/936

Fix the issue about fsync on hostfs's dir

---

.github/workflows/demo_test.yml
.github/workflows/hw_mode_test.yml
.github/workflows/main.yml

1. Do not change download source in hw_mode_test
2. Support "Cancel previous running jobs on push or pull request", make sure only one active workflow from **the same PR, branch or tag**

[ci] Cancel previous running jobs on Push/PR

---

demos/linux-ltp/syscalls-occlum

It will introduce too much overhead if we check the memory protection perm for every user space address, so we dismiss the test case.

Fix the SEGV in LTP test

---

tools/gen_internal_conf/src/main.rs

`pkru` field has been introduced in the Occlum.json since Occlum 0.28.0. Users may encounter failure in `occlum build` if they use legacy Occlum.json, since there is no `pkru` field in it. To work around it, we specify the default value of `pkru` as 0 for its missing in Occlum.json.

Set the default pkru value at Occlum.json's parse

---

tools/docker/Dockerfile.anolis8.4
tools/docker/README.md
tools/docker/build_image.sh

Add a dockerfile named 'Dockerfile.anolis8.4' for building occlum image for Anolis 8.4.
1. The SGX SDK version in the docker file has been updated to 2.17.
2. Notice is commented at the top line of the docker file that anolis is not an official supported distribution now.

Add anolis 8.4 docker image support

---

test/Makefile
test/test_common.mk

In default, `make test` requires the Occlum build first.
It also provides an option that is to specify the path of Occlum binary.
`OCCLUM_BIN_PATH=/opt/occlum/build/bin make test`

[test] No need build Occlum to make test

---

tools/installer/deb/toolchains/golang/rules
tools/installer/rpm/toolchains/golang/occlum-toolchains-golang.spec
tools/toolchains/golang/build.sh

In default, occlum-go uses musl-gcc. Users can configure occlum-go to use gcc like below.
" CC=gcc occlum-go build "

[toolchain] Make occlum-go support gcc/glibc option

---

src/libos/src/fs/sefs/mod.rs
src/libos/src/fs/sefs/sgx_storage.rs

This PR configure **cache size** of underlying SGX-PFS of SEFS to **1MiB** (default 192KiB).
Larger cache size can acclerate file I/O of SEFS.
(20% ~ 70% reads/writes improvemenet according to FIO test)

[sefs] Configure larger cache size to improve pfs performance

---

demos/README.md
demos/mysql/.gitignore
demos/mysql/README.md
demos/mysql/apply-mysql-to-occlum.patch
demos/mysql/dl_and_build_mysql.sh
demos/mysql/my.cnf
demos/mysql/mysql.yaml
demos/mysql/run_mysql_client.sh
demos/mysql/run_mysql_server.sh
src/libos/crates/async-socket/src/stream/mod.rs
src/libos/crates/vdso-time/src/lib.rs
src/libos/src/time/mod.rs

This PR includes:
1. Workaround `CLOCK_PROCESS_CPUTIME_ID` and `CLOCK_THREAD_CPUTIME_ID` in `clock_gettime()`. The syscall with either these two flags would end up calling `vdso_ocall_clock_gettime()`.
2. Improve `ioctl()` in stream socket: Refine state transfer.
3. Add MySQL to demo list.

Improve clock_gettime, stream socket and add MySQL demo

---

.github/workflows/benchmarks.yml
.github/workflows/hw_mode_test.yml

1. Enable benchmark ci on schedule(Wed,Sat at 10PM UTC (6AM CST)) only on branch 1.0.0-preview
2. Improve hw ci: a. run on schedule(Tue,Fri at 6PM UTC (2AM CST)) b. lower stress test times under given limit(360 min)

Improve benchmark ci and hw ci

---

.github/workflows/composite_action/hw/action.yml

To avoid network port conflict between different runners.

[ci] Do not run container with network host for hw ci

---

src/libos/src/vm/process_vm.rs
src/libos/src/vm/vm_manager.rs

Test with the command `TESTS=mmap make test times=2000` and pass.

Fix mremap lock range when merging connecting chunks

---

src/libos/src/vm/user_space_vm.rs
src/libos/src/vm/vm_perms.rs

Tested with SDK 2.18 and EDMM-enabled platform.

Fix reserved memory permission for EDMM support

---

etc/template/Occlum.yaml
src/libos/src/config.rs
src/libos/src/fs/rootfs.rs
src/libos/src/fs/sefs/mod.rs
src/libos/src/fs/sefs/sgx_storage.rs
test/Occlum.yaml
tools/gen_internal_conf/src/main.rs

Similar modification in https://github.com/occlum/occlum/pull/1142
This PR
1. add `sefs_cache_size` to `ConfigMount.options`
2. rename `total_size` to `async_sfs_total_size` to avoid ambiguity

[sefs] Make cache size configurable in Occlum.yaml

---

src/libos/crates/block-device/src/util/mod.rs
src/libos/crates/jindisk/src/util/mod.rs
src/libos/crates/sgx-untrusted-alloc/src/untrusted_allocator/vm_util.rs
src/libos/src/prelude.rs

The `is_power_of_two()` ensures the alignment is not zero.

[libos] Fix the align_up & align_down assertions in prelude

---

tools/toolchains/glibc/build.sh

The libcrypt.so built from glibc doesn't have "XCRYPT_2.0" section.
Using crypt implementation coming from libxcrypt which is installed already in Ubuntu 20.04.

[glibc] No need build libcrypt from glibc

---

src/libos/crates/jindisk/src/checkpoint/bitc.rs
src/libos/crates/jindisk/src/checkpoint/dst.rs
src/libos/crates/jindisk/src/checkpoint/key_table.rs
src/libos/crates/jindisk/src/checkpoint/mod.rs
src/libos/crates/jindisk/src/config.rs
src/libos/crates/jindisk/src/data/cache.rs
src/libos/crates/jindisk/src/data/cleaning.rs
src/libos/crates/jindisk/src/data/mod.rs
src/libos/crates/jindisk/src/index/bit/builder.rs
src/libos/crates/jindisk/src/index/bit/disk_bit.rs
src/libos/crates/jindisk/src/index/bit/mem_bit.rs
src/libos/crates/jindisk/src/index/compaction.rs
src/libos/crates/jindisk/src/index/reclaim.rs
src/libos/crates/jindisk/src/jindisk.rs
src/libos/crates/jindisk/src/prelude.rs
src/libos/crates/jindisk/src/util/disk_range.rs
src/libos/crates/jindisk/src/util/mod.rs

This PR adds a new feature: threaded logging to JinDisk.
Threaded-logging enables JinDisk to log data in seperate blocks rather big segment. It triggers when disk space is running out. It automatically disables when background GC freed some segments. Foreground GC is no longer needed thanks to threaded logging.

[jindisk] Support threaded logging

---

src/libos/src/syscall/syscall_entry_x86-64.S

Same as https://github.com/occlum/occlum/pull/1197, fix https://github.com/occlum/occlum/issues/1196.
The pervious implementation of `occlum_sysret` misuses the red zone, which breaches the System V ABI.
At the prologue and epilogue of syscall handling functions, we need to perform the following operations:
1. Check whether to change the value of PRKU register;
2. If the condition in 1. is true, change the value of PKRU register.
These operations may overwrites several registers, such as FLAGS, %rax, %rdx and %rcx. We use the stack area below the red zone to save and restore the register above.

[libos] Retain red zone area and FLAGS unmodified across syscall

---

src/libos/src/entry/context_switch/switch_x86-64.S

1. The previous implementation of __occlum_syret usse the red zone to save the register temporarily, which may overwrite the red zone area. This change avoids using the red zone when handling syscall.
2. Save and restore the FLAGS register before and after the operations on PKRU to keep the FLAGS unmodified.

Retain red zone area and FLAGS unmodified across syscall

---

test/cpuid/main.c

For new x86 processors, CPUID leaf 1FH is introduced as the V2 Extended Topology Enumeration and is a prefered superset to leaf 0BH.
Add extra case to skip the EDX check because the corresponding value is related with logical processor (x2APIC ID).

[test] Fix false alarm for cpuid test

---

src/libos/crates/async-sfs/src/fs.rs
src/libos/crates/async-sfs/src/lib.rs
src/libos/crates/block-device/src/util/block_range.rs
src/libos/crates/jindisk/src/data/cleaning.rs
src/libos/crates/jindisk/src/jindisk.rs
src/libos/crates/page-cache/src/cached_disk.rs
src/libos/crates/page-cache/src/lib.rs
src/libos/crates/page-cache/src/prelude.rs
src/libos/crates/page-cache/tests/cached_disk_tests.rs

This PR optimizes read performance in AsyncSFS by enable batch read of consecutive blocks when a read request touches multi blocks.
A FIO benchmark comparison (seqwr-256k / randwr-32k / seqrd-256k / randrd-32k)
Before optimization:
After optimization:

[async-sfs&page-cache] Support batch read of consecutive blocks

---

src/libos/Cargo.lock
src/libos/Cargo.toml
src/libos/crates/Cargo.lock
src/libos/crates/async-rt/src/task/locals.rs
src/libos/src/entry/enclave.rs
src/libos/src/entry/exception/mod.rs
src/libos/src/entry/syscall.rs
src/libos/src/entry/thread.rs
src/libos/src/fs/file_ops/fsync.rs
src/libos/src/fs/procfs/meminfo.rs
src/libos/src/fs/procfs/pid/maps.rs
src/libos/src/ipc/shm.rs
src/libos/src/ipc/syscalls.rs
src/libos/src/lib.rs
src/libos/src/misc/sysinfo.rs
src/libos/src/process/do_clone.rs
src/libos/src/process/do_exec.rs
src/libos/src/process/do_exit.rs
src/libos/src/process/do_spawn/init_vm.rs
src/libos/src/process/do_spawn/mod.rs
src/libos/src/signal/do_sigreturn.rs
src/libos/src/vm/chunk.rs
src/libos/src/vm/free_space_manager.rs
src/libos/src/vm/mod.rs
src/libos/src/vm/process_vm.rs
src/libos/src/vm/user_space_vm.rs
src/libos/src/vm/vm_area.rs
src/libos/src/vm/vm_chunk_manager.rs
src/libos/src/vm/vm_manager.rs
src/libos/src/vm/vm_util.rs

Prerequisite: Merge https://github.com/occlum/occlum/pull/1243 first
This PR asynchronizes Occlum's VM subsystem.
1. `mmap()`, `munmap()`, `mremap()`, `mprotect()`, `brk()`, `msync()`, `shmget()`, `shmdt()`, `sgmctl()`, `sysinfo()` are async functions now.
2. Do not rely `ProcessVM::Drop` for error handling, instead of hooking error handler in process spawn after VM initialized.
3. The change affects exception, signal, process, procfs, ipc subsystems.
Hw mode ci is tested [here](https://github.com/lucassong-mh/occlum/actions/runs/4817347977).

[vm] Asynchronize vm subsystem to adapt AsyncSFS

---

src/libos/src/net/io_multiplexing/poll_new/mod.rs

Fix a bug recently introduced by the support of negative poll_fd.

[poll] Fix panic for non-opened fds

---

.github/workflows/build_and_push_ci_image.yml

Due to limited resources of Github Actions' hosted machine, we changed to build this image on our self-hosted machine.

Fix building TF serving image failure

---

etc/template/Occlum.yaml
src/libos/src/fs/mod.rs
src/libos/src/fs/rootfs.rs
src/libos/src/fs/sefs/mod.rs
src/libos/src/fs/sefs/sgx_storage.rs
src/libos/src/util/sgx/mod.rs
src/libos/src/util/sgx/sgx_key.rs

The root key of JinDisk can now be obtained from 1. user-given key 2. derive with user-given key policy 3. derive with default key policy - `SGX_KEYPOLICY_MRSIGNER` (which behavior is similar to SGX-PFS's autokey generation: [pos](https://github.com/occlum/linux-sgx/blob/sgx_2.19_for_ngo/sdk/protected_fs/sgx_tprotected_fs/file_crypto.cpp#L207))
When using derived key, some key metadata (key_id, cpu_svn, isv_svn) are persisted to an untrusted file (similar to PFS's metadata node). The file stands next to jindisk's image path.

[jindisk] Support get the root key given key policy

---

src/libos/src/net/socket/mod.rs
src/libos/src/net/socket/msg.rs
src/libos/src/net/socket/unix/stream/endpoint.rs
src/libos/src/net/socket/unix/stream/stream.rs

This PR adds support for unix stream socket to send/receive msg_control, see [cmsg](https://man7.org/linux/man-pages/man3/cmsg.3.html). The control messages are mainly used for send/receive file descriptors.
Having this feature, `sendmsg()`/`recvmsg()` of unix socket can parse, extract, reassign fd in `msg_control`.

[net] Support send/receive control message in unix socket

---

src/libos/crates/jindisk/README.md
src/libos/crates/jindisk/src/checkpoint/mod.rs
src/libos/crates/jindisk/src/checkpoint/rit.rs
src/libos/crates/jindisk/src/config.rs
src/libos/crates/jindisk/src/data/cache.rs
src/libos/crates/jindisk/src/data/cleaning.rs
src/libos/crates/jindisk/src/index/bit/builder.rs
src/libos/crates/jindisk/src/index/bit/mem_bit.rs
src/libos/crates/jindisk/src/index/compaction.rs
src/libos/crates/jindisk/src/index/reclaim.rs
src/libos/crates/jindisk/src/jindisk.rs
src/libos/crates/jindisk/src/lib.rs
src/libos/crates/jindisk/src/superblock.rs
src/libos/crates/jindisk/src/util/cryption.rs
src/libos/crates/jindisk/src/util/disk_array.rs

This PR includes:
1. Add symm cryption API (AES-128-CTR) and apply to `DiskArray` @cqs21 https://github.com/occlum/occlum/pull/1289
2. Refactor cryption API (refer to [rust-openssl](https://docs.rs/openssl/0.10.54/openssl/symm/index.html))
3. Improve block reclamation part in compaction
4. Rename `trim()` to `discard()` for more accuracy in block device layer. Add an implementation, leave performance impact `TODO`.

[jindisk] Improve block cryption, reclaim and discard

---

src/libos/src/entry.rs
src/libos/src/events/waiter.rs
src/libos/src/events/waiter_queue.rs
src/libos/src/net/io_multiplexing/epoll/epoll_file.rs
src/libos/src/process/do_futex.rs
src/libos/src/process/do_robust_list.rs
src/libos/src/process/task/mod.rs
src/libos/src/process/term_status.rs
src/libos/src/untrusted/slice_alloc.rs

https://github.com/occlum/occlum/blob/f54eabfa92319490e1b13075b28fef2d3d9129fd/src/libos/src/entry.rs#L26
HAS_INIT need to synchronize the relevant resources in interrupt::init(). The read operation of HAS_INIT needs to see the change of the resources. I think just Acquire/Release needs to be used here to ensure the correctness of the program.
https://github.com/occlum/occlum/blob/f54eabfa92319490e1b13075b28fef2d3d9129fd/src/libos/src/events/waiter_queue.rs#L30
https://github.com/occlum/occlum/blob/f54eabfa92319490e1b13075b28fef2d3d9129fd/src/libos/src/events/waiter_queue.rs#L42
https://github.com/occlum/occlum/blob/f54eabfa92319490e1b13075b28fef2d3d9129fd/src/libos/src/events/waiter_queue.rs#L68
I think count needs to be synchronized with waker. The read operation of count needs to see …

Fune-tune the Ordering for all the atomics

---

src/libos/src/ipc/shm.rs
src/libos/src/vm/mod.rs
src/libos/src/vm/process_vm.rs
src/libos/src/vm/shm_manager.rs
src/libos/src/vm/vm_area.rs
src/libos/src/vm/vm_manager.rs

This PR fixes an early munmap bug in posix shm, inspired by https://github.com/occlum/occlum/issues/1392
TODO: Add the multi-thread rust demo that could testify the above bugfix

[vm] Avoid early munmap of shm

---

tools/copy_bom/README.md
tools/copy_bom/example.yaml
tools/copy_bom/src/bom.rs

The original way to get filename is incorrect for directories which end with '/'.
For path like `/dev/pts/`, if we use the original way,
```rust
let pathbuf = PathBuf::from("/dev/pts/");
let filename = pathbuf.filename().unwrap(); 
```
`filename` will be `pts`. However, an empty filename is indeed what we want.

Enable copy_bom to find dependences directories which end with '/'

---

src/libos/src/net/socket/host/mod.rs
src/libos/src/net/socket/host/recv.rs
src/libos/src/net/socket/host/send.rs
src/libos/src/untrusted/slice_alloc.rs

This PR improve 50% tcp performance by reducing ocalls.

Improve network performance by reducing ocalls

---

.github/workflows/composite_action/hw/action.yml
demos/java/run_java_on_occlum.sh
demos/python/python_glibc/python3.10-multiprocessing/run_python3.10_on_occlum.sh
demos/sofaboot/.gitignore
docs/pku_manual.md
docs/readthedocs/docs/source/occlum_configuration.md
etc/template/Occlum.json
src/libos/src/config.rs
src/libos/src/vm/shm_manager.rs
src/libos/src/vm/vm_manager.rs
test/Occlum.json
tools/gen_internal_conf/src/main.rs

This PR includes:
1. A new configurable field "feature" is added in Occlum.json. Two features are now supported: "pkru" and "enable_posix_shm".
2. Minor improvement in shared chunk expansion in shm: Add current process to the shared set when there is a `NeedExpand` for two chunks.
3. Enable all features on hw ci for EDMM.

[config] Add "feature" field to Occlum.json
