- .gitignore
- .gitmodules
Signed-off-by: Jia Zhang <zhang.jia@linux.alibaba.com>
> Define .gitignore to ignore generated files

- README.md
Signed-off-by: danintel <daniel.anderson@intel.com>
> Fix README.md: Minor Corrections

- src/libos/src/entry.rs
> Check the MPX status of platform before enabling

- docs/rune_quick_start.md
1. Update CentOS dockerimage to 7.5
2. Allow users to define OCCLUM_INSTANCE_DIR
> Update RunE Quick Start doc

- .travis.yml
Put format checking to containers.
> Fix travis test script

- src/pal/pal.lds
- src/pal/src/pal_api.c
Signed-off-by: jack.wxz <wangxiaozhe@linux.alibaba.com>
> Use pal api interface without prefix of libos type.

- tools/occlum
- tools/occlum_build.mk
Fixes #139 
This PR is dependent on the PR of SEFS(https://github.com/occlum/sefs/pull/4), remember to update the submodule after the SEFS is updated.
> Change the calling interface with sefs-cli

- docs/occlum_mount.md
> Add prerequisite part of the doc for "occlum mount"

- demos/golang/go_sqlite/.gitignore
- demos/golang/go_sqlite/README.md
- demos/golang/go_sqlite/run_go_sqlite_demo.sh
- demos/golang/go_sqlite/simple_demo.go
> Add Golang SQLite demo

- src/Enclave.edl
- src/libos/src/events/event.rs
- src/libos/src/events/host_event_fd.rs
- src/libos/src/events/mod.rs
- src/libos/src/events/notifier.rs
- src/libos/src/events/observer.rs
- src/libos/src/events/waiter.rs
- src/libos/src/events/waiter_queue.rs
- src/libos/src/events/waiter_queue_observer.rs
- src/libos/src/lib.rs
- src/libos/src/process/thread/builder.rs
- src/libos/src/process/thread/mod.rs
- src/libos/src/signal/do_sigtimedwait.rs
- src/libos/src/signal/mod.rs
- src/libos/src/signal/sig_num.rs
- src/libos/src/signal/sig_queues.rs
- src/libos/src/signal/sig_set.rs
- src/libos/src/signal/syscalls.rs
- src/libos/src/syscall/mod.rs
- src/libos/src/time/mod.rs
- src/pal/src/ocalls/event.c
- src/pal/src/ocalls/fs.c
- src/pal/src/pal_syscall.h
- test/signal/main.c
This syscall implementation is based on the event subsystem (#158 ). So need to wait that PR to be merged first.
> Add sigtimedwait syscall

- src/libos/Cargo.lock
- src/libos/Cargo.toml
- src/libos/src/events/host_event_fd.rs
- src/libos/src/fs/channel.rs
- src/libos/src/fs/events.rs
- src/libos/src/fs/mod.rs
- src/libos/src/fs/pipe.rs
- test/pipe/main.c
1. Introduce channels, which provide an efficient means for IPC;
2. Leverage channels to rewrite pipe, improving the performance (3X), robustness, and readability.
This pipe rewrite is not done: some more commits will be added to implement poll and epoll for pipe.
> Refactor pipe with the new event subsystem

- demos/golang/grpc_pingpong/go.mod
- demos/golang/grpc_pingpong/pong.go
in cmd/protoc-gen-go-grpc.
This patch will resolve issue https://github.com/occlum/occlum/issues/173.
> Fix an issue caused by recent reverted gRPC service registration interfaces

- demos/sqlite/download_and_build_sqlite.sh
- demos/sqlite/run_sqlite_on_occlum.sh
Add the SQLite speedtest for performance benchmark
> Add the SQLite benchmark app

- .github/workflows/demo_test.yml
Enable Golang web server, Golang gRPC, and Golang SQLite tests for CI
> Add Golang SQLite test for CI

- demos/xgboost/download_and_build_xgboost.sh
- demos/xgboost/install_cmake.sh
- demos/xgboost/patch/dmlc-core-01.diff
- demos/xgboost/patch/rabit-01.diff
- demos/xgboost/patch/xgboost-01.diff
Intel has optimized the xgboost in latest version. Performance has
obvious acceleration in benchmark. In svm training with Yahoo LTR data,
latest version gets 7.8X acceleration in host, and 2X acceleration in occlum.
> Update the xgboost to latest version

- docs/resource_config_guide.md
- src/libos/src/error/to_errno.rs
- src/libos/src/fs/sefs/sgx_storage.rs
Fixes #146 
This commit depends on https://github.com/occlum/sefs/pull/6, please remember to update sefs before merging.
> Report the SGX protected file I/O error

- src/libos/src/fs/file_ops/ioctl/mod.rs
- test/ioctl/main.c
> Add ioctl support for FIONBIO command

- src/libos/src/net/socket/host_socket/recv.rs
- test/server_epoll/main.c
There is a CI test failure related to `server_epoll` test. These two commits help to mitigate and diagnose the failure.
> Fix the CI test failure

- .github/workflows/main.yml
- README.md
- src/exec/Cargo.lock
- src/exec/Cargo.toml
- src/libos/Cargo.lock
- src/libos/Cargo.toml
- src/pal/include/occlum_version.h
> Bump version to 0.17.0

- .github/workflows/package_repo_setup_and_test.yml
I tested with my own repo and the results can be seen [here](https://github.com/jessehui/occlum/actions/runs/321499229).
> Add package deployment and test action

- docs/rune_quick_start.md
1. Rename rune_quick_start to running_Occlum_with_Docker_and_OCI_Runtime_rune
2. Running Occlum application with docker and rune instead of Occlum application bundle
3. Update to occlum-0.17.0 and rune-0.5.0
4. Using Occlum installer instead of Occlum sdk image to build Occlum application
> Update Inclavare Containers Quick Start doc

- src/libos/src/process/do_spawn/init_stack.rs
Libc ABI requires 16-byte alignment of the stack entrypoint
> Fix the alignment of stack entrypoint

- src/sgxenv.mk
The tcmalloc only works under HW mode.
> Replace dlmalloc with tcmalloc

- .github/workflows/hw_mode_test.yml
Currently, only a subset of tests are enabled. Other tests will be enabled in the future.
Results can be checked here: https://github.com/jessehui/occlum/actions/runs/369797484
> Add SGX hardware mode test

- src/libos/src/fs/channel.rs
- src/libos/src/fs/event_file.rs
- src/libos/src/fs/events.rs
- src/libos/src/fs/file.rs
- src/libos/src/fs/mod.rs
- src/libos/src/net/io_multiplexing/epoll/epoll_file.rs
- src/libos/src/net/io_multiplexing/epoll/host_file_epoller.rs
- src/libos/src/net/io_multiplexing/mod.rs
- src/libos/src/net/io_multiplexing/poll_new/event_monitor.rs
- src/libos/src/net/io_multiplexing/poll_new/mod.rs
- src/libos/src/net/io_multiplexing/select.rs
- src/libos/src/net/socket/host_socket/socket_file.rs
- src/libos/src/net/syscalls.rs
- src/libos/src/time/mod.rs
- test/pipe/main.c
In addition to the new select implementation, this PR also contains two bugfixes for `Channel`.
> Rewrite the select syscall using the new poll implementation

- src/libos/src/process/do_futex.rs
- src/libos/src/process/syscalls.rs
- src/libos/src/syscall/mod.rs
Depends on https://github.com/occlum/linux-sgx/pull/8, remember to merge the PR in SGX SDK first
> Add FUTEX_WAIT_BITSET and FUTEX_WAKE_BITSET

- .github/workflows/hw_mode_test.yml
1. Enable gRPC test
2. Always clean the docker
3. Support parallel jobs
Results can be checked here: https://github.com/jessehui/occlum/actions/runs/371637799
> Enhance SGX hardware mode CI test

- .github/workflows/demo_test.yml
- README.md
1. Ignore the result for grpc demo test in CI
2. Add new CI status badge for different workflow
> Ignore the grpc demo test result for simulation mode

- .github/workflows/rune_test.yml
1. Always run pods
2. Always clean the docker
3. Support parallel jobs
> Enhance rune CI test

- src/libos/src/fs/rootfs.rs
> Add support to mount FS at any existing directories

- tools/docker/Dockerfile.centos8.1
- tools/docker/Dockerfile.ubuntu18.04
Lcov will be used for code coverage generation.
> Install lcov in occlum docker images

- .github/workflows/build_and_push_ci_image.yml
- .github/workflows/hw_mode_test.yml
- tools/docker/ci/Dockerfile.gvisor
Two commits are included. One is to use CI to build docker image. The other is to add gvisor test to hardware mode CI test.
> Add gvisor ci

- src/libos/src/util/mem_util.rs
The added check can detect negative count, too.
> Fix multiplication overflow

- tools/occlum
> Enhance the check before running an instance

- test/signal/main.c
There may be a pthread_detach bug. Use pthread_join to workaround it.
> Use pthread_join to wait for the async thread to exit

- .github/workflows/build_and_push_docker_image.yml
- .github/workflows/hw_mode_test.yml
- .github/workflows/main.yml
These commits make debug easy.
> Add trace log for CI make test and fix docker buildx log output size

- .github/workflows/hw_mode_test.yml
- Makefile
- deps/rust-sgx-sdk.patch
- docs/code_coverage.md
- src/Makefile
- src/libos/Cargo.lock
- src/libos/Cargo.toml
- src/libos/Makefile
- src/libos/src/misc/coverage.rs
- src/libos/src/misc/mod.rs
The code coverage uses sgx_cov of Rust SGX SDK. It is ahead of the SDK version we are using, so a 885-line patch is committed together.
> Add codecov

- README.md
- etc/template/Occlum.json
- src/libos/Cargo.lock
- src/libos/Cargo.toml
- src/libos/src/config.rs
- src/libos/src/fs/dev_fs/dev_null.rs
- src/libos/src/fs/dev_fs/dev_random.rs
- src/libos/src/fs/dev_fs/dev_sgx/mod.rs
- src/libos/src/fs/dev_fs/dev_zero.rs
- src/libos/src/fs/dev_fs/mod.rs
- src/libos/src/fs/events.rs
- src/libos/src/fs/file_ops/mod.rs
- src/libos/src/fs/fs_view.rs
- src/libos/src/fs/inode_file.rs
- src/libos/src/fs/mod.rs
- src/libos/src/fs/rootfs.rs
- src/libos/src/lib.rs
- src/libos/src/net/io_multiplexing/mod.rs
- src/libos/src/net/io_multiplexing/poll.rs
- test/Occlum.json
- tools/gen_internal_conf/src/main.rs
- tools/occlum
Add DevFS for all device files
> Add DevFS for all device files

- src/libos/src/fs/file_ops/dirent.rs
- test/readdir/main.c
> Fix getdents cannot output all entries in a directory

- tools/occlum
Fix: https://github.com/occlum/occlum/issues/312
> Ignore AESM status for simulation mode

- README.md
> Remove HW CI test result, because the SGX machine has networking issue

- .github/workflows/demo_test.yml
- demos/redis/README.md
- demos/redis/benchmark.sh
- demos/redis/benchmark_glibc.sh
- demos/redis/download_and_build_redis.sh
- demos/redis/download_and_build_redis_glibc.sh
- demos/redis/run_occlum_redis.sh
- demos/redis/run_occlum_redis_glibc.sh
> Add the redis demo

- tools/installer/README.md
Update the installer README to align with the current status
> Update the installer README file

- .github/workflows/demo_test.yml
- demos/flink/README.txt
- demos/flink/download_flink.sh
- demos/flink/hosts
- demos/flink/run_flink_jobmanager_on_host.sh
- demos/flink/run_flink_on_occlum_glibc.sh
> Add the flink demo

- src/libos/src/process/do_spawn/exec_loader.rs
This commit can prevent panic when user input:
occlum run /bin
> Fix panic for non-specified exec file path

- tools/docker/Dockerfile.centos7.5
- tools/docker/Dockerfile.centos8.1
- tools/docker/Dockerfile.centos8.2
- tools/docker/Dockerfile.ubuntu18.04
A much needed improvement when working with the provided Docker images :)
> Add nano to Dockerfiles

- .github/workflows/demo_test.yml
- demos/golang/vault/README.md
- demos/golang/vault/prepare_vault.sh
- demos/golang/vault/run_occlum_vault_server.sh
- demos/golang/vault/run_occlum_vault_test.sh
Partially implements [issue#386](https://github.com/occlum/occlum/issues/386).
Signed-off-by: Kailun Qin <kailun.qin@intel.com>
> Add the HashiCorp Vault demo

- src/libos/src/fs/pipe.rs
- test/pipe/main.c
> Add fstat support for pipe

- .github/workflows/build_and_push_alinux2_image.yml
- tools/docker/Dockerfile.aliyunlinux
Related: https://github.com/occlum/occlum/issues/379
> Add dockerfile for Aliyun Linux image

- src/libos/src/vm/vm_manager.rs
- test/mmap/main.c
The test case covered every branch.
> Add support for mremap with file-backed memory

- README.md
https://community.intel.com/t5/Intel-Software-Guard-Extensions/Intel-SGX-Linux-Driver-Cheat-Sheet-dev-sgx-vs-dev-isgx/td-p/1184174
> Add docker example for SGX DCAP driver

- docs/install_occlum_packages.md
* Add tzdata & libsgx-dcap-quote-verify-dev into install package
> Fix locatime & quote verify shared lib

- src/libos/src/net/mod.rs
- src/libos/src/net/socket/mod.rs
- src/libos/src/net/socket/msg.rs
- src/libos/src/net/syscalls.rs
- src/libos/src/syscall/mod.rs
- test/client/main.c
- test/server/main.c
sendmmsg is a Linux syscall used by glibc
> Add sendmmsg syscall

- src/libos/src/fs/file.rs
- src/libos/src/fs/fs_ops/mod.rs
- src/libos/src/fs/fs_ops/statfs.rs
- src/libos/src/fs/hostfs.rs
- src/libos/src/fs/inode_file.rs
- src/libos/src/fs/mod.rs
- src/libos/src/fs/procfs/mod.rs
- src/libos/src/fs/syscalls.rs
- src/libos/src/syscall/mod.rs
- test/Makefile
- test/procfs/main.c
- test/statfs/Makefile
- test/statfs/main.c
Fixes #398 
Remember to merge this first:
https://github.com/occlum/sefs/pull/19
> Add statfs and fstatfs syscall

- src/libos/src/fs/file.rs
- src/libos/src/fs/file_ops/file_flags.rs
- src/libos/src/fs/fs_ops/mod.rs
- src/libos/src/fs/fs_ops/statfs.rs
- src/libos/src/fs/hostfs.rs
- src/libos/src/fs/inode_file.rs
- src/libos/src/fs/mod.rs
- src/libos/src/fs/procfs/mod.rs
- src/libos/src/fs/sefs/sgx_storage.rs
- src/libos/src/fs/syscalls.rs
- src/libos/src/syscall/mod.rs
- test/Makefile
- test/fs_perms/main.c
- test/hostfs/main.c
- test/include/test.h
- test/include/test_fs.h
- test/mmap/main.c
- test/procfs/main.c
- test/statfs/Makefile
- test/statfs/main.c
- test/truncate/main.c
Fix the "O_TRUNC support" in issue https://github.com/occlum/occlum/issues/354
Remember to merge https://github.com/occlum/sefs/pull/16 first
> Add O_TRUNC support in open syscall and rewrite truncate test

- src/libos/src/fs/channel.rs
- src/libos/src/fs/file_ops/ioctl/mod.rs
- src/libos/src/fs/pipe.rs
- src/libos/src/net/socket/unix/stream/file.rs
- test/ioctl/main.c
- test/naughty_child/main.c
- test/pipe/main.c
- test/unix_socket/main.c
> Add support for ioctl FIONREAD, FIOCLEX, FIONCLEX for pipe and uds file

- src/libos/src/net/socket/unix/addr.rs
- src/libos/src/net/socket/unix/stream/address_space.rs
- src/libos/src/net/socket/unix/stream/stream.rs
- src/libos/src/net/syscalls.rs
- test/unix_socket/main.c
Include two commits:
- Add support for indexing unix domain socket file with inode
- Add dummy implementation of getsockopt for unix domain socket
> Fix unix domain socket when enabling Java UT

- .github/workflows/build_and_push_docker_image.yml
- tools/docker/Dockerfile.aliyunlinux
- tools/docker/Dockerfile.centos8.2
- tools/docker/Dockerfile.ubuntu18.04
1. Make "bash" the default shell when building image
2. Add libarchive dependency for centos image
Based on #472
> Fix dockerfile error

- .github/workflows/package_repo_setup_and_test.yml
- docs/install_occlum_packages.md
- src/exec/Cargo.lock
- src/exec/Cargo.toml
- src/libos/Cargo.lock
- src/libos/Cargo.toml
- src/pal/include/occlum_version.h
- test/exit_group/main.c
- tools/docker/Dockerfile.aliyunlinux
- tools/docker/Dockerfile.centos8.2
- tools/docker/Dockerfile.ubuntu18.04
Fix DCAP version in centos image.
> Update occlum version

- .github/workflows/hw_mode_test.yml
> Fix HW mode unit test build issue

- demos/enclave_tls/run_enclave_tls_server_in_occlum.sh
Signed-off-by: Shirong Hao <shirong@linux.alibaba.com>
> Update enclave-tls demo test

- .github/workflows/hw_mode_test.yml
> Fix hw mode demo test failure issues

- .github/workflows/hw_mode_test.yml
> Fix go webserver test cmd error

- demos/openvino/download_and_build_openvino.sh
- demos/openvino/run_benchmark_on_occlum.sh
1. Replace the original TBB with OneTBB v2020.3
2. Replace the 2019_R3 with DLDT 2021.3
3. Add some dependent lib to the occlum image
> Add support for OpenVINO 2021.3

- src/libos/src/signal/do_sigtimedwait.rs
> Add signal check before sigtimedwait return with timeout

- demos/fish/fish_script.sh
- src/libos/Cargo.lock
- src/libos/src/fs/file_ops/fspath.rs
- src/libos/src/fs/file_ops/mod.rs
- src/libos/src/fs/syscalls.rs
- src/libos/src/syscall/mod.rs
> Add support for fchdir and support cd for fish

- .gitmodules
- Makefile
- demos/grpc/run_client_on_occlum.sh
- demos/grpc/run_server_on_occlum.sh
- deps/resolv-conf.patch
- src/Enclave.edl
- src/libos/Cargo.toml
- src/libos/src/entry.rs
- src/libos/src/fs/fs_ops/mount.rs
- src/libos/src/lib.rs
- src/libos/src/util/mod.rs
- src/libos/src/util/resolv_conf_util.rs
- src/pal/src/pal_api.c
- src/pal/src/pal_load_resolv_conf.c
- src/pal/src/pal_load_resolv_conf.h
- test/Makefile
- test/resolv_conf/Makefile
- test/resolv_conf/main.c
Add the resolv.conf parser. #422
> Add resolv.conf parser

- README.md
- demos/fish/Occlum.json
- etc/template/Occlum.json
- test/Occlum.json
- tools/occlum
Fixes #570 
Merge https://github.com/occlum/sefs/pull/26 first
> Remove the mount config for tmp dir

- src/libos/src/entry.rs
- src/libos/src/process/do_wait4.rs
- src/libos/src/process/mod.rs
- src/libos/src/vm/user_space_vm.rs
This can fix memory leakage when parent not wait4 children.
> Reap zombie children when exit

- src/libos/src/net/io_multiplexing/poll_new/event_monitor.rs
When no events happen, the state of host file events will not be reset,
so the event_monitor should always update the state after polling files.
> Fix the event_monitor when updating host file events

- demos/cluster_serving/init-occlum-taskmanager.sh
> Fix manual lib copy in cluster serving demo

- tools/occlum
> Make it accordance for occlum package name and extracted dir name

- .github/workflows/demo_test.yml
- demos/README.md
- demos/bash/.gitignore
- demos/bash/Occlum.json
- demos/bash/README.md
- demos/bash/occlum_bash_test.sh
- demos/bash/prepare_bash_demo.sh
- demos/bash/run_bash_demo.sh
Bash change: https://github.com/occlum/bash/pull/1
> Add Bash demo

- src/libos/Cargo.lock
- src/libos/src/error/to_errno.rs
- src/libos/src/fs/file.rs
- src/libos/src/fs/file_ops/fallocate.rs
- src/libos/src/fs/file_ops/mod.rs
- src/libos/src/fs/inode_file.rs
- src/libos/src/fs/mod.rs
- src/libos/src/fs/syscalls.rs
- test/file/main.c
- test/include/test_fs.h
Merge https://github.com/occlum/sefs/pull/23 first
> Add support for the mode of fallocate

- README.md
> Fix SGX device softlinks creation issue

- src/Enclave.edl
- src/libos/include/edl/occlum_edl_types.h
- src/libos/src/fs/fs_ops/statfs.rs
- src/pal/include/edl/occlum_edl_types.h
- src/pal/src/ocalls/fs.c
> Modify the statfs on SEFS or UnionFS with ocall

- src/libos/src/fs/dev_fs/dev_random.rs
- src/libos/src/fs/sefs/sgx_uuid_provider.rs
- src/libos/src/misc/mod.rs
- src/libos/src/misc/random.rs
- src/libos/src/process/do_spawn/init_stack.rs
- src/libos/src/syscall/mod.rs
- src/libos/src/util/mod.rs
- src/libos/src/vm/process_vm.rs
- test/Makefile
- test/random/Makefile
- test/random/main.c
> Add getrandom syscall

- demos/bash/Occlum.json
- demos/fish/Occlum.json
- demos/remote_attestation/dcap/c_app/dcap_c_test.c
- demos/remote_attestation/dcap/dcap_lib/examples/dcap_test.rs
- etc/template/Occlum.json
- src/pal/src/base64.c
- src/pal/src/base64.h
- src/pal/src/pal_enclave.c
- test/Occlum.json
- tools/gen_internal_conf/src/main.rs
- tools/occlum
Implementaion for RFC (`Add SGX KSS (Key Separation and Sharing feature) support on Occlum`)[https://github.com/occlum/occlum/issues/589](url).
> Add SGX V2 KSS feature support

- tools/toolchains/glibc/build.sh
> Fix the error when building glibc with gcc 9

- demos/remote_attestation/dcap/dcap_lib/examples/dcap_test.rs
> Fix dangling buffer pointer bug in dcap demo

- .github/workflows/build_and_push_aliyunlinux_image.yml
- .github/workflows/build_and_push_docker_image.yml
- tools/docker/Dockerfile.aliyunlinux3
- tools/docker/Dockerfile.centos8.2
- tools/docker/Dockerfile.ubuntu18.04
- tools/docker/README.md
- tools/docker/build_image.sh
> Use toolchains from the git clone source instead of from the local path

- demos/remote_attestation/dcap/dcap.yaml
- demos/remote_attestation/dcap/run_dcap_quote_on_occlum.sh
> Update dcap demo with copy_bom tool

- .github/workflows/demo_test.yml
- demos/cluster_serving/cluster_serving.yaml
- demos/cluster_serving/init-occlum-taskmanager.sh
- demos/python/python_musl/python_musl.yaml
- demos/python/python_musl/run_python_on_occlum.sh
- demos/pytorch/install_python_with_conda.sh
- demos/pytorch/pytorch.yaml
- demos/pytorch/run_pytorch_on_occlum.sh
- demos/sofaboot/run_sofaboot_on_occlum.sh
- demos/sofaboot/sofaboot.yaml
- demos/tensorflow/tensorflow_serving/run_occlum_tf_serving.sh
- demos/tensorflow/tensorflow_serving/tensorflow_serving.yaml
- demos/tensorflow/tensorflow_training/run_tensorflow_on_occlum.sh
- demos/tensorflow/tensorflow_training/tensorflow_training.yaml
demos for sofaboot, cluster serving, pytorch, tensorflow, python-musl
> Update copy_bom demos

- .github/workflows/code_coverage.yaml
> Add code coverage action test

- .github/workflows/demo_test.yml
- demos/openvino/openvino.yaml
> Fix bom tool autodep issue for openvino

- codecov.yml
> Add codecov ignore path

- test/server/main.c
> Fix timing issue in test_sendmsg_recvmsg_connectionless

- .github/workflows/code_coverage.yaml
> Enable OCCLUM_LOG_LEVEL=trace for code coverage test

- src/libos/src/process/do_spawn/mod.rs
- src/libos/src/vm/process_vm.rs
- src/libos/src/vm/vm_manager.rs
> Fix running user application with too many arguments

- .github/workflows/composite_action/action.yml
- .github/workflows/demo_test.yml
- .github/workflows/main.yml
Abstract the common steps, occlum container creation, source build and install into one composite action.
In this way, much repetitive code could be removed.
> Create composite action for occlum container run and src build/install

- src/libos/src/util/mem_util.rs
This commit fixed an Occlum security issue. The researchers from KU
Leuven (Belgium) and the University of Birmingham (UK) found it and
reported it to Occlum team. Thank you, Jo Van Bulck, Frank Piessens,
Fritz Alder, David Oswald, Jesse Spielman and Sam Thomas.
> Check the buffer address before copy the data from the buffer

- src/libos/src/entry.rs
- src/libos/src/fs/fs_ops/mount.rs
- src/libos/src/fs/fs_ops/sync.rs
- src/libos/src/fs/fs_view.rs
- src/libos/src/fs/mod.rs
- src/libos/src/fs/rootfs.rs
The filesystem should be the owner of its root inode, so we should record the fs in occlum
Remember to merge https://github.com/occlum/sefs/pull/42
> [libos] Change ROOT_INODE to ROOT_FS

- src/libos/src/fs/file_table.rs
- src/libos/src/process/do_vfork.rs
Same as NGO PR: https://github.com/occlum/ngo/pull/197
> Fix vfork child process not close opened files

- Makefile
- tools/docker/Dockerfile.aliyunlinux3
- tools/docker/Dockerfile.centos8.2
- tools/docker/Dockerfile.ubuntu18.04
This reverts commit 4c99c875e7bddec85431ddb883adea58b7e530cd.
> Build and install dcap lib when make submodule

- .github/workflows/demo_test.yml
- src/libos/src/process/do_exec.rs
- src/libos/src/process/do_futex.rs
- src/libos/src/process/syscalls.rs
- tools/docker/Dockerfile.ubuntu20.04
Requires: https://github.com/occlum/linux-sgx/pull/18
> Fix futex failure in gvisor test

- .github/workflows/package_repo_setup_and_test.yml
- tools/installer/README.md
- tools/installer/deb/Makefile
- tools/installer/deb/toolchains/musl-gcc/changelog
Verified here: https://github.com/jessehui/occlum/actions/runs/1956101315
> Support apt repo and deb packages for ubuntu 20.04

- .github/workflows/hw_mode_test.yml
- demos/remote_attestation/init_ra_flow/run_till_ready.sh
- docs/remote_attestation.md
1. Fix bug in init_ra HW CI.
2. Delete ra_tls HW CI case since it is almost covered in init_ra demo.
3. Add some brief introduction about init_ra in the doc remote_attestation.
> Fix init_ra HW action timing issue

- Makefile
- deps/sefs-cli_hyper.patch
- src/libos/Cargo.toml
- src/libos/Enclave.lds
- src/libos/Makefile
- src/libos/src/net/mod.rs
- src/libos/src/net/socket/host/recv.rs
- src/libos/src/net/socket/host/send.rs
- src/libos/src/untrusted/mod.rs
- src/libos/src/untrusted/slice_alloc.rs
- src/libos/src/util/sgx/epid/attestation_agent.rs
- src/libos/src/util/sgx/epid/quote.rs
- src/pal/Makefile
- src/pal/src/pal_api.c
- src/pal/src/pal_ms_buffer.c
- src/pal/src/pal_ms_buffer.h
- src/sgxenv.mk
- test/cpuid/main.c
- test/ioctl/main.c
- test/test_common.mk
- tools/Makefile
- tools/gen_internal_conf/Cargo.toml
- tools/gen_internal_conf/Makefile
- tools/gen_internal_conf/src/main.rs
- tools/occlum
This PR adds the support for hyper mode.
> Add support for hyper mode

- src/libos/src/ipc/mod.rs
- src/libos/src/ipc/shm.rs
- src/libos/src/ipc/syscalls.rs
- src/libos/src/lib.rs
- src/libos/src/process/do_exit.rs
- src/libos/src/process/mod.rs
- src/libos/src/syscall/mod.rs
- src/libos/src/vm/mod.rs
- src/libos/src/vm/process_vm.rs
- src/libos/src/vm/user_space_vm.rs
- test/Makefile
- test/shm/Makefile
- test/shm/main.c
1. Add support for System V shared memory;
2. Add some tests for it
More details are shown in #863
> [libos] Add support for shm

- src/libos/src/fs/event_file.rs
- src/libos/src/fs/file_ops/file_flags.rs
- src/libos/src/fs/file_ops/mod.rs
- src/libos/src/fs/inode_file.rs
- src/libos/src/fs/mod.rs
- src/libos/src/fs/stdio.rs
- src/libos/src/fs/timer_file.rs
- src/libos/src/net/socket/host/socket_file.rs
> [libos] Add status_flags support for stdio

- README.md
- etc/template/Occlum.json
- src/Enclave.edl
- src/libos/Cargo.toml
- src/libos/Makefile
- src/libos/include/task.h
- src/libos/src/entry.rs
- src/libos/src/process/do_spawn/mod.rs
- src/libos/src/syscall/syscall_entry_x86-64.S
- src/libos/src/util/mod.rs
- src/libos/src/util/pku_util.rs
- src/libos/src/vm/user_space_vm.rs
- src/pal/src/ocalls/mem.c
- test/Occlum.json
- tools/gen_internal_conf/src/main.rs
- Upgrade rust-sgx-sdk to 2.16
- Support PKU feature mentioned in this [issue](https://github.com/occlum/ngo/issues/243).
> Support PKU for Occlum

- src/exec/Cargo.lock
- src/exec/Cargo.toml
- src/libos/Cargo.lock
- src/libos/Cargo.toml
- src/pal/include/occlum_version.h
Signed-off-by: volcano0dr <volcano_dr@163.com>
> Bump to 0.27.3

- .github/workflows/composite_action/hw/action.yml
The network of new ci machine works fine so we disable proxy and ustc crates-io source.
> [hw_ci] Disable proxy and ustc crates-io source on new machine

- .github/workflows/composite_action/hw/action.yml
- .github/workflows/hw_mode_test.yml
1. Remove GO PROXY since the network work well. The original configuration may cause network error randomly;
2. Update the url of PCCS server
> Fix some issues in CI (Branch 0.28.0)

- src/libos/src/net/socket/unix/stream/stream.rs
> Fix typo in stream.rs

- .github/workflows/demo_test.yml
- demos/golang/go_sqlite/run_go_sqlite_demo.sh
- demos/golang/grpc_pingpong/prepare_ping_pong.sh
- tools/toolchains/golang/adapt-golang1.18.4-to-occlum.patch
- tools/toolchains/golang/build.sh
Signed-off-by: Lan Yun <yun.lan@intel.com>
> update toolchain golang version to 1.18.4

- src/libos/src/fs/file_ops/fspath.rs
- src/libos/src/fs/file_ops/getdents.rs
- src/libos/src/fs/syscalls.rs
- src/libos/src/net/socket/unix/addr.rs
After the updates, should merge https://github.com/occlum/sefs/pull/48 first
> Fix the max path limit

- src/libos/src/fs/file_ops/fspath.rs
- src/libos/src/fs/file_ops/getdents.rs
- src/libos/src/fs/file_ops/link.rs
- src/libos/src/fs/file_ops/mkdir.rs
- src/libos/src/fs/file_ops/rename.rs
- src/libos/src/fs/file_ops/rmdir.rs
- src/libos/src/fs/file_ops/symlink.rs
- src/libos/src/fs/file_ops/unlink.rs
- src/libos/src/fs/fs_view.rs
- src/libos/src/fs/mod.rs
- src/libos/src/fs/rootfs.rs
- src/libos/src/fs/syscalls.rs
- src/libos/src/net/socket/unix/addr.rs
- test/hostfs/main.c
- test/mkdir/main.c
- test/open/main.c
- test/rename/main.c
- test/stat/main.c
Rewrite this PR.
and this commit deps on https://github.com/occlum/occlum/pull/974
> Fix the issue when path is suffixed by "/"

- src/libos/src/net/socket/unix/stream/address_space.rs
- src/libos/src/net/socket/unix/stream/file.rs
- src/libos/src/net/socket/unix/stream/stream.rs
- src/libos/src/net/syscalls.rs
- test/unix_socket/Makefile
- test/unix_socket/main.c
> Add sendmsg/recvmsg support for unix domain socket

- .github/workflows/build_and_push_docker_image.yml
- demos/golang/vault/prepare_vault.sh
- src/libos/src/vm/chunk.rs
- src/libos/src/vm/vm_manager.rs
- test/mmap/Makefile
- test/mmap/main.c
Also add CI ability to build dev image. The dev image will be look like: `occlum/occlum:latest-dev-[SHA]-ubuntu20.04`.
Also fix the vault demo build failure due to its dependency `go-limiter` failure. For more info, check this out: https://github.com/hashicorp/vault/pull/12358
> Fix munmap conflict range

- tools/copy_bom/src/bom.rs
- tools/copy_bom/src/error.rs
- tools/copy_bom/src/util.rs
This PR is about RFC #991. Similar to #981, but do additional check before copy_bom aborts.
> [tools] Fix copy_bom sliently exit when autodep fails

- tools/copy_bom/src/error.rs
- tools/copy_bom/src/main.rs
- tools/copy_bom/src/util.rs
> Fix copy_bom error message if rsync is not installed

- .github/workflows/package_repo_setup_and_test.yml
- tools/installer/deb/toolchains/glibc/rules
Verified: https://github.com/occlum/occlum/actions/runs/3124770227/jobs/5068623013
> Add glibc toolchain deb build and test actions

- demos/python/python_glibc/install_python_with_conda.sh
- demos/python/python_glibc/run_python_on_occlum.sh
- demos/pytorch/install_python_with_conda.sh
- demos/tensorflow/tensorflow_training/install_python_with_conda.sh
Modify the miniconda selected python version to 3.8 instead of 3.7, plus some pip packages version updates.
> Fix python3.7 PIE issue

- demos/mysql/.gitignore
- demos/mysql/README.md
- demos/mysql/apply-mysql-to-occlum.patch
- demos/mysql/dl_and_build_mysql.sh
- demos/mysql/my.cnf
- demos/mysql/mysql.yaml
- demos/mysql/run_mysql_client.sh
- demos/mysql/run_mysql_server.sh
This PR adds MySQL demo to Occlum's demo list.
Run step:
1. Download mysql-8.0.31 and build dependencies
2. Build from src (Need to apply patch to disable `HAVE_TIMES`)
3. Run mysql server and test mysql client
> [demos] Add MySQL demo

- .github/workflows/hw_mode_test.yml
- demos/mysql/dl_and_build_mysql.sh
- demos/mysql/my.cnf
- demos/mysql/mysql.yaml
- demos/mysql/run_benchmarks.sh
- demos/mysql/run_mysql_server.sh
Test [here](https://github.com/lucassong-mh/occlum/actions/runs/3785040146/jobs/6434785766) and [here](https://github.com/lucassong-mh/occlum/actions/runs/3785607902/jobs/6435791841)
> [hw-ci] Add MySQL to hw mode test

- src/libos/src/vm/vm_manager.rs
> Fix mmap with MAP_FIXED non-atomic behaviour

- .github/workflows/benchmarks.yml
- .github/workflows/hw_mode_test.yml
1. Disable benchmark test on push
2. Improve schedule of benchmark ci and hw ci
> [ci] Improve schedule in benchmark ci and hw ci

- src/libos/src/util/sgx/dcap/quote_verifier.rs
This commit fixed a security issue in the dcap verifier. The issue was caused by the `[in, out]` attributes of pointer parameter `qve_report_info` in the ocall function `occlum_ocall_verify_dcap_quote()`. This led to the vulnerability where the protected `qve_report_info.nonce` field in libos could be arbitrarily rewritten by attacker outside libos.
Here is a simple proof of the attack.
For illustration purposes, we add two statements to quote_verifier.rs, which will print the contents of qve_report_info.nonce before and after the call to oclum_ocall_verify_dcap_quote(). Then we added a statement in src/pal/src/ocalls/attestation.c to act as an attacker on the ocall side who will modify the nonce value.
```patch
diff --git a/src/libos/src/util/sgx/dcap/quote_verifier.rs …
```
> [libos] Fix vulnerable nonce in DCAP verifier

- src/libos/src/util/sgx/dcap/quote_verifier.rs
This commit fixed a security issue in the dcap verifier. The issue was caused by the '[in, out]' attributes of pointer parameter qve_report_info in the ocall function occlum_ocall_verify_dcap_quote(). This led to the vulnerability where the protected qve_report_info.nonce field in libos could be arbitrarily rewritten by attacker outside libos.
Signed-off-by: Kun Lai <me@imlk.top>
> Fix vulnerable nonce in DCAP verifier

- .github/workflows/code_coverage.yaml
- tools/docker/ci/Dockerfile.gvisor_test
Require: https://github.com/occlum/gvisor/pull/20
> Fix gvisor failure in code coverage test

- src/libos/src/vm/process_vm.rs
- src/libos/src/vm/vm_manager.rs
> Fix mremap lock range when merging connecting chunks

- src/libos/src/config.rs
- src/libos/src/fs/rootfs.rs
- src/libos/src/fs/sefs/mod.rs
- src/libos/src/fs/sefs/sgx_storage.rs
- tools/gen_internal_conf/src/main.rs
> [sefs] Make cache size configurable in Occlum.json

- test/client/main.c
Due to scheduling, the client could attempt to connect to the server before the server starts to accept. Make the client retry multiple times before returning with error.
> Fix potential server test failure

- src/libos/crates/async-sfs/src/fs.rs
- src/libos/src/fs/file_ops/getdents.rs
- src/libos/src/fs/hostfs.rs
- src/libos/src/fs/procfs/mod.rs
- src/libos/src/fs/procfs/pid/fd.rs
- src/libos/src/fs/procfs/pid/mod.rs
- src/libos/src/fs/procfs/proc_inode/mod.rs
Pls merge https://github.com/occlum/sefs/pull/53 first, then I will update this commit.
> [libos] Refine the getdents syscall

- .github/workflows/benchmarks.yml
- .github/workflows/demo_test.yml
- .github/workflows/hw_mode_test.yml
- demos/flink/README.md
- demos/flink/download_flink.sh
- demos/flink/preinstall_deps.sh
- demos/mysql/README.md
- demos/mysql/dl_and_build_mysql.sh
- demos/mysql/preinstall_deps.sh
- demos/mysql/run_benchmarks.sh
- demos/netty_ut/README
- demos/netty_ut/build.sh
- demos/netty_ut/preinstall_deps.sh
- demos/xgboost/README.md
- demos/xgboost/download_and_build_xgboost.sh
- demos/xgboost/install_cmake.sh
- demos/xgboost/preinstall_deps.sh
This PR includes:
1. Enable AsyncSFS+JinDisk test on branch 1.0.0-preview in benchmark ci
2. Make dependency preinstallation seperately in script and demonstrated in README. This can bring benefits on os checks and script reentrant
> [demos] Improve steps of dependency preinstall

- src/libos/crates/async-socket/src/stream/states/listen.rs
This should fix the slow shutdown/close for the socket.
> [async-socket] Limit the number of listen backlog for async accept request

- demos/bash/occlum_bash_test.sh
- demos/benchmarks/sysbench/dl_and_build.sh
- demos/deployment/README.md
- demos/enclave_tls/README.md
- demos/fish/README.md
- demos/fish/test_per_process_config.sh
- demos/grpc/grpc_musl/README.md
- demos/grpc/grpc_tls/README.md
- demos/grpc/grpc_tls/greeter_secure_server.cc
- demos/local_attestation/AppInitiator/UntrustedEnclaveMessageExchange.cpp
- demos/local_attestation/AppInitiator/UntrustedEnclaveMessageExchange.h
- demos/local_attestation/AppInitiator/app.cpp
- demos/local_attestation/AppInitiator/fifo.cpp
- demos/local_attestation/AppResponder/session.c
- demos/local_attestation/DiffieHellmanLibrary/DiffieHellmanLibrary.patch
- demos/local_attestation/EnclaveInitiator/EnclaveInitiator.cpp
- demos/local_attestation/EnclaveInitiator/EnclaveMessageExchange.cpp
- demos/local_attestation/download_src_and_build_deps.sh
- demos/openvino/0001-Fix-passing-pre-increment-parameter-cpu-to-CPU_ISSET.patch
- demos/python/flask/gen-cert.sh
- demos/pytorch/distributed/README.md
typo errors in different dirs including doc/comment typo error and code typo error
> [typo fix] fix some typo errors 

- src/libos/src/fs/dev_fs/dev_fd.rs
- src/libos/src/fs/dev_fs/dev_null.rs
- src/libos/src/fs/dev_fs/dev_sgx/mod.rs
- src/libos/src/fs/dev_fs/dev_shm.rs
- src/libos/src/fs/dev_fs/dev_zero.rs
- src/libos/src/fs/hostfs.rs
- src/libos/src/fs/procfs/proc_inode/dir.rs
- src/libos/src/fs/procfs/proc_inode/file.rs
- src/libos/src/fs/procfs/proc_inode/symlink.rs
Please merge https://github.com/occlum/sefs/pull/56 first
> Use the default poll implementation of INode

- src/libos/src/net/io_multiplexing/poll_new/mod.rs
> Fix poll misbehavior with negative pollfd value

- src/libos/src/net/io_multiplexing/poll_new/mod.rs
> Refine poll handle negative poll_fds

- .github/workflows/demo_test.yml
- demos/README.md
- demos/swtpm/README.md
- demos/swtpm/install_swtpm.sh
- demos/swtpm/run_client.sh
- demos/swtpm/run_swtpm.sh
- demos/swtpm/swtpm.yaml
This PR:
- adds software trusted platform module (SWTPM) to run inside SGX
- test script for IBM's TPM2.0 TSS
Tested on Azure confidential Computing Environment (_Standard DC2ds v3_) with Ubuntu 20.04.
> add swtpm demo

- tools/occlum
This is added for debugging purposes and should be removed. Please rebase it next to "Add new fields for config file to enable EDMM" and merge these two commits. The current commit message can be ignored.
> Fix "Add new fields for config file to enable EDMM"

- docs/readthedocs/docs/source/init_ra.md
aquire -> acquire
aquired -> acquired
> [readthedoc] Fix typo in init_ra.md

- src/libos/Cargo.lock
- src/libos/src/fs/file.rs
- src/libos/src/fs/file_ops/getdents.rs
- src/libos/src/fs/hostfs.rs
- src/libos/src/fs/inode_file.rs
- src/libos/src/fs/mod.rs
- src/libos/src/fs/procfs/mod.rs
- src/libos/src/fs/procfs/pid/fd.rs
- src/libos/src/fs/procfs/pid/mod.rs
- src/libos/src/fs/procfs/proc_inode/dir.rs
- src/libos/src/fs/procfs/proc_inode/mod.rs
Please merge https://github.com/occlum/sefs/pull/60, then I will update this commit.
> Rewrite the getdents

- demos/bigdl-llm/README.md
- demos/bigdl-llm/benchmarks/bench.py
- demos/bigdl-llm/chatglm2/generate.py
- demos/bigdl-llm/chatglm2/streamchat.py
- demos/bigdl-llm/install_python_with_conda.sh
- demos/bigdl-llm/model_convert.py
Update bigdl-llm demo with latest ipex llm.
> [demos] Update llm demo with latest ipex-llm

- .github/workflows/composite_action/prebuild/action.yml
- .gitmodules
- Makefile
- deps/mlsdisk.patch
- docs/readthedocs/docs/source/filesystem/fs_overview.md
- docs/readthedocs/docs/source/occlum_configuration.md
- docs/readthedocs/docs/source/tutorials/gen_occlum_instance.md
- etc/template/base.yaml
- src/Enclave.edl
- src/libos/Cargo.lock
- src/libos/Cargo.toml
- src/libos/src/blk/dev_disk.rs
- src/libos/src/blk/mod.rs
- src/libos/src/blk/raw_disk.rs
- src/libos/src/config.rs
- src/libos/src/fs/dev_fs/mod.rs
- src/libos/src/fs/fs_ops/mount.rs
- src/libos/src/fs/rootfs.rs
- src/libos/src/fs/stdio.rs
- src/libos/src/lib.rs
- src/libos/src/process/mod.rs
- src/libos/src/time/mod.rs
- src/libos/src/util/sgx/mod.rs
- src/libos/src/util/sgx/sgx_key.rs
- tools/gen_internal_conf/src/main.rs
- tools/occlum
See the RFC: https://github.com/occlum/occlum/issues/1539
> Support configurable Ext2+SwornDisk

- .github/workflows/demo_test.yml
- demos/benchmarks/filebench/.gitignore
- demos/benchmarks/filebench/README.md
- demos/benchmarks/filebench/apply-filebench-to-occlum.patch
- demos/benchmarks/filebench/dl_and_build_filebench.sh
- demos/benchmarks/filebench/filebench.yaml
- demos/benchmarks/filebench/preinstall_deps.sh
- demos/benchmarks/filebench/run_workload.sh
- demos/benchmarks/filebench/workloads/fileserver.f
- demos/benchmarks/filebench/workloads/oltp.f
- demos/benchmarks/filebench/workloads/readfiles.f
- demos/benchmarks/filebench/workloads/varmail.f
- demos/benchmarks/filebench/workloads/videoserver.f
1. Add Filebench tool
2. Run a micro benchmark to test Ext2 on CI
> Add Filebench demo and enable it on CI to test Ext2 
